// GENERATED by scripts/gen_diagnostic_registry.py from schema/diagnostics.json.
// These are the only core-allocated codes the frontend emits.
export const diagnosticCodes = {
  duplicateWorkspaceOutput: "E125",
  unknownWorkspaceRef: "E126",
  workspaceCycle: "E127",
  badWorkspaceContext: "E128",
  invalidWorkspaceValue: "E130",
} as const;
