// GENERATED by scripts/gen_diagnostic_registry.py from schema/diagnostics.json.
// These are the only core-allocated codes the frontend emits.
export const diagnosticCodes = {
  duplicateWorkspaceOutput: "E125",
  unknownWorkspaceRef: "E126",
  workspaceCycle: "E127",
  badWorkspaceContext: "E128",
  invalidWorkspaceValue: "E130",
} as const;

export const frontendDiagnosticCodeRegistry = {
  E125: true,
  E126: true,
  E127: true,
  E128: true,
  E130: true,
} as const satisfies Record<string, true>;
