//! Bounded Rust↔Go bridge protocol (Epic B §4/§10.3, plan/0051 B1
//! fences). One framed structured transport: every frame is a
//! length-prefixed JSON body whose declared length is checked against
//! [`MAX_FRAME_BYTES`] BEFORE the body is read, so a hostile peer can
//! never turn a header into an allocation. Artifacts never travel in
//! JSON — only digests, bounded log chunks and terminal facts.
//!
//! The Go bridge (B0's qualified client APIs, later `tools/
//! buildkit-bridge`) and this crate share these wire shapes; both
//! sides decode strictly (unknown fields reject) and every event
//! carries the session's fence epoch so stale, duplicate or
//! conflicting attempts cannot authorize anything.

use serde::{Deserialize, Serialize};
use std::fmt;

/// Absolute frame cap. Log/event frames are far smaller; export
/// receipts carry digests, never bytes. Checked against the length
/// header before any body allocation.
pub const MAX_FRAME_BYTES: usize = 256 * 1024;

/// Per-event log chunk cap (matches the supervisor's retained-tail
/// bound; coalescing may not turn truncation into false success).
pub const MAX_LOG_CHUNK_BYTES: usize = 64 * 1024;

/// Protocol version this core speaks; the bridge negotiates or the
/// session refuses to start. Pinned pair, never a range.
pub const PROTOCOL_VERSION: u32 = 1;

/// sha256 hex digest, exactly 64 lowercase characters.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct Digest(String);

#[derive(Debug, thiserror::Error)]
#[error("digest must be 64 lowercase hex characters, got {0}")]
pub struct DigestError(String);

impl Digest {
    pub fn of(bytes: &[u8]) -> Self {
        use sha2::{Digest as _, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(bytes);
        let mut hex = String::with_capacity(64);
        for byte in hasher.finalize() {
            hex.push_str(&format!("{byte:02x}"));
        }
        Self(hex)
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for Digest {
    type Error = DigestError;
    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() == 64
            && value
                .bytes()
                .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit())
        {
            Ok(Self(value))
        } else {
            Err(DigestError(value))
        }
    }
}

impl From<Digest> for String {
    fn from(digest: Digest) -> Self {
        digest.0
    }
}

impl fmt::Display for Digest {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Session identity: opaque bounded ASCII, generated by the core.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct SessionId(String);

impl SessionId {
    pub fn new(value: impl Into<String>) -> Result<Self, String> {
        let value = value.into();
        let ok = !value.is_empty()
            && value.len() <= 64
            && value
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_');
        if ok {
            Ok(Self(value))
        } else {
            Err(format!(
                "session id must be 1..=64 ASCII alphanumerics, '-' or '_' — got {value:?}"
            ))
        }
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for SessionId {
    type Error = String;
    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<SessionId> for String {
    fn from(id: SessionId) -> Self {
        id.0
    }
}

/// Core → bridge. `Submit` binds the EXACT checked bytes: the bridge
/// must send the definition whose digest it acknowledged, never
/// rebuild or merge ambient options (Epic B §10.3 step 4).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub enum ToBridge {
    Negotiate {
        protocol_version: u32,
        capabilities: Vec<String>,
    },
    Submit {
        session: SessionId,
        /// Digest + length of the independently validated LLB
        /// definition and exporter config this submission is bound to.
        definition: Digest,
        definition_len: u64,
        exporter: Digest,
    },
    /// Idempotent: cancelling an unknown/finished session is not an
    /// error, but never silently retries the work.
    Cancel { session: SessionId },
}

/// Bridge → core. Terminal variants are exactly `Done`, `Failed`,
/// `Cancelled`; one is accepted per session (see [`EventGate`]).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub enum FromBridge {
    NegotiateOk {
        protocol_version: u32,
        daemon_version: String,
        capabilities: Vec<String>,
    },
    Accepted {
        session: SessionId,
        epoch: u64,
    },
    Event {
        session: SessionId,
        epoch: u64,
        #[serde(flatten)]
        kind: BridgeEvent,
    },
    Exported {
        session: SessionId,
        epoch: u64,
        /// Declared outputs with their content digests and sizes —
        /// bytes move through the store, never this channel.
        outputs: Vec<ExportedOutput>,
    },
    Done {
        session: SessionId,
        epoch: u64,
    },
    Failed {
        session: SessionId,
        epoch: u64,
        code: FailureCode,
        message: String,
    },
    Cancelled {
        session: SessionId,
        epoch: u64,
    },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub enum BridgeEvent {
    Log {
        vertex: String,
        #[serde(with = "log_chunk")]
        chunk: Vec<u8>,
        truncated: bool,
    },
    Progress {
        vertex: String,
        message: String,
    },
}

/// Log chunks are base64 on the wire with the decoded size checked
/// against [`MAX_LOG_CHUNK_BYTES`] after decode (the frame cap already
/// bounds the encoded form before allocation).
mod log_chunk {
    use super::MAX_LOG_CHUNK_BYTES;
    use base64::{Engine, engine::general_purpose::STANDARD};
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(chunk: &[u8], serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&STANDARD.encode(chunk))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Vec<u8>, D::Error> {
        let encoded = String::deserialize(deserializer)?;
        let chunk = STANDARD.decode(encoded).map_err(serde::de::Error::custom)?;
        if chunk.len() > MAX_LOG_CHUNK_BYTES {
            return Err(serde::de::Error::custom(format!(
                "log chunk exceeds {MAX_LOG_CHUNK_BYTES} bytes"
            )));
        }
        Ok(chunk)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExportedOutput {
    pub name: String,
    pub digest: Digest,
    pub size: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FailureCode {
    Rejected,
    WorkerDied,
    ExportFailed,
    InvalidOutput,
    Internal,
}

#[derive(Debug, thiserror::Error)]
pub enum ProtocolError {
    #[error("frame header declares {0} bytes; the protocol caps frames at {1}")]
    OversizedFrame(u64, usize),
    #[error("frame body is {0} bytes but its header declared {1}")]
    TruncatedFrame(usize, u64),
    #[error("invalid frame JSON: {0}")]
    Malformed(#[source] serde_json::Error),
    #[error("bridge sent {0} bytes of trailing garbage after a frame")]
    TrailingBytes(usize),
    #[error("bridge negotiated protocol {0}; this core speaks {1} exactly")]
    VersionMismatch(u32, u32),
    #[error("negotiation expected NegotiateOk, got {0:?}")]
    NotNegotiate(String),
}

/// A complete frame: little-endian u64 byte length + JSON body. The
/// length is validated against the cap BEFORE the body is taken, so
/// decoding hostile bytes never allocates beyond [`MAX_FRAME_BYTES`].
#[derive(Debug, Clone, PartialEq)]
pub struct Frame<B> {
    pub body: B,
}

pub fn encode_frame<M: Serialize>(message: &M) -> Vec<u8> {
    let body = serde_json::to_vec(message).expect("protocol messages serialize");
    debug_assert!(
        body.len() <= MAX_FRAME_BYTES,
        "encoder produced an oversized frame"
    );
    let mut frame = Vec::with_capacity(8 + body.len());
    frame.extend_from_slice(&(body.len() as u64).to_le_bytes());
    frame.extend_from_slice(&body);
    frame
}

pub fn decode_frame<B: for<'de> Deserialize<'de>>(bytes: &[u8]) -> Result<Frame<B>, ProtocolError> {
    let Some(header) = bytes.first_chunk::<8>() else {
        return Err(ProtocolError::TruncatedFrame(bytes.len(), 0));
    };
    let declared = u64::from_le_bytes(*header);
    if declared > MAX_FRAME_BYTES as u64 {
        return Err(ProtocolError::OversizedFrame(declared, MAX_FRAME_BYTES));
    }
    let body_end = 8 + declared as usize;
    if bytes.len() < body_end {
        return Err(ProtocolError::TruncatedFrame(bytes.len() - 8, declared));
    }
    if bytes.len() > body_end {
        return Err(ProtocolError::TrailingBytes(bytes.len() - body_end));
    }
    let body = serde_json::from_slice(&bytes[8..body_end]).map_err(ProtocolError::Malformed)?;
    Ok(Frame { body })
}

/// Negotiation: one exact version pair, intersection of capabilities.
/// A mismatched bridge is refused before any session exists.
pub fn negotiate(reply: &FromBridge) -> Result<Vec<String>, ProtocolError> {
    match reply {
        FromBridge::NegotiateOk {
            protocol_version,
            capabilities,
            ..
        } if *protocol_version == PROTOCOL_VERSION => Ok(capabilities.clone()),
        FromBridge::NegotiateOk {
            protocol_version, ..
        } => Err(ProtocolError::VersionMismatch(
            *protocol_version,
            PROTOCOL_VERSION,
        )),
        other => Err(ProtocolError::NotNegotiate(format!("{other:?}"))),
    }
}

/// Pure fence state machine for one session's bridge→core events
/// (plan/0051 B1 fences): events are accepted only for the live epoch
/// and a session accepts exactly one terminal outcome. Cancellation
/// fences acceptance immediately — a late `Done` after `Cancelled` is
/// a stale event, not a flip.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EventGate {
    epoch: u64,
    terminal: Option<Terminal>,
    logs_emitted: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Terminal {
    Done,
    Failed,
    Cancelled,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum GateError {
    #[error("event epoch {0} is stale; the session fence is at {1}")]
    StaleEpoch(u64, u64),
    #[error("event epoch {0} jumps ahead of the session fence {1}")]
    FutureEpoch(u64, u64),
    #[error("session is already terminal ({0:?}); a late event cannot flip it")]
    AlreadyTerminal(Terminal),
    #[error("log flood: {0} event chunks exceed the {1} chunk budget")]
    LogBudget(u64, u64),
}

impl EventGate {
    pub const MAX_LOG_EVENTS: u64 = 4096;

    pub fn new(epoch: u64) -> Self {
        Self {
            epoch,
            terminal: None,
            logs_emitted: 0,
        }
    }

    fn check(&self, epoch: u64) -> Result<(), GateError> {
        if self.terminal.is_some() {
            // Report the staleness first: a terminal session fences
            // every later event, including same-epoch ones.
            return Err(GateError::AlreadyTerminal(
                self.terminal.unwrap_or(Terminal::Done),
            ));
        }
        match epoch.cmp(&self.epoch) {
            std::cmp::Ordering::Less => Err(GateError::StaleEpoch(epoch, self.epoch)),
            std::cmp::Ordering::Greater => Err(GateError::FutureEpoch(epoch, self.epoch)),
            std::cmp::Ordering::Equal => Ok(()),
        }
    }

    pub fn log(&mut self, epoch: u64) -> Result<(), GateError> {
        self.check(epoch)?;
        self.logs_emitted += 1;
        if self.logs_emitted > Self::MAX_LOG_EVENTS {
            return Err(GateError::LogBudget(
                self.logs_emitted,
                Self::MAX_LOG_EVENTS,
            ));
        }
        Ok(())
    }

    pub fn observe(&mut self, epoch: u64) -> Result<(), GateError> {
        self.check(epoch)
    }

    /// Terminal acceptance: exactly one of Done/Failed/Cancelled.
    /// A duplicate terminal — even the same variant — is rejected so a
    /// confused bridge cannot double-report an outcome.
    pub fn terminal(&mut self, epoch: u64, terminal: Terminal) -> Result<(), GateError> {
        self.check(epoch)?;
        self.terminal = Some(terminal);
        Ok(())
    }

    pub fn terminal_state(&self) -> Option<Terminal> {
        self.terminal
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip<B>(message: B) -> B
    where
        B: Serialize + for<'de> Deserialize<'de> + PartialEq + std::fmt::Debug,
    {
        let frame = encode_frame(&message);
        let decoded: Frame<B> = decode_frame(&frame).expect("round trip decodes");
        decoded.body
    }

    #[test]
    fn every_message_round_trips_byte_exactly() {
        let session = SessionId::new("build-1a").unwrap();
        let to = [
            ToBridge::Negotiate {
                protocol_version: PROTOCOL_VERSION,
                capabilities: vec!["llb.v1".into()],
            },
            ToBridge::Submit {
                session: session.clone(),
                definition: Digest::of(b"definition"),
                definition_len: 10,
                exporter: Digest::of(b"exporter"),
            },
            ToBridge::Cancel {
                session: session.clone(),
            },
        ];
        for message in to {
            assert_eq!(round_trip(message.clone()), message);
        }
        let from = [
            FromBridge::NegotiateOk {
                protocol_version: PROTOCOL_VERSION,
                daemon_version: "v0.33.0".into(),
                capabilities: vec!["llb.v1".into()],
            },
            FromBridge::Accepted {
                session: session.clone(),
                epoch: 7,
            },
            FromBridge::Event {
                session: session.clone(),
                epoch: 7,
                kind: BridgeEvent::Log {
                    vertex: "gcc".into(),
                    chunk: b"compiling\n".to_vec(),
                    truncated: false,
                },
            },
            FromBridge::Event {
                session: session.clone(),
                epoch: 7,
                kind: BridgeEvent::Progress {
                    vertex: "export".into(),
                    message: "writing layer".into(),
                },
            },
            FromBridge::Exported {
                session: session.clone(),
                epoch: 7,
                outputs: vec![ExportedOutput {
                    name: "tool".into(),
                    digest: Digest::of(b"tool"),
                    size: 933_288,
                }],
            },
            FromBridge::Done {
                session: session.clone(),
                epoch: 7,
            },
            FromBridge::Failed {
                session: session.clone(),
                epoch: 7,
                code: FailureCode::WorkerDied,
                message: "buildkitd exited".into(),
            },
            FromBridge::Cancelled {
                session: session.clone(),
                epoch: 7,
            },
        ];
        for message in from {
            assert_eq!(round_trip(message.clone()), message);
        }
    }

    #[test]
    fn hostile_headers_reject_before_any_body_is_read() {
        let mut frame = vec![0u8; 8];
        let huge = (MAX_FRAME_BYTES as u64 + 1).to_le_bytes();
        frame.copy_from_slice(&huge);
        // Trailing body bytes prove the header is rejected first: a
        // length-cap hit never depends on the body's content.
        frame.extend_from_slice(&[0xff; 4096]);
        let result: Result<Frame<FromBridge>, _> = decode_frame(&frame);
        assert!(matches!(
            result,
            Err(ProtocolError::OversizedFrame(declared, _)) if declared as usize > MAX_FRAME_BYTES
        ));

        let truncated = &(encode_frame(&ToBridge::Cancel {
            session: SessionId::new("s").unwrap(),
        }))[..10];
        let result: Result<Frame<ToBridge>, _> = decode_frame(truncated);
        assert!(matches!(result, Err(ProtocolError::TruncatedFrame(_, _))));
    }

    #[test]
    fn trailing_bytes_and_unknown_fields_reject() {
        let mut frame = encode_frame(&ToBridge::Cancel {
            session: SessionId::new("s").unwrap(),
        });
        frame.push(b'{');
        let result: Result<Frame<ToBridge>, _> = decode_frame(&frame);
        assert!(matches!(result, Err(ProtocolError::TrailingBytes(1))));

        let body = r#"{"Negotiate":{"protocol_version":1,"capabilities":[],"surprise":true}}"#;
        let mut hostile = (body.len() as u64).to_le_bytes().to_vec();
        hostile.extend_from_slice(body.as_bytes());
        let result: Result<Frame<ToBridge>, _> = decode_frame(&hostile);
        assert!(matches!(result, Err(ProtocolError::Malformed(_))));
    }

    #[test]
    fn log_chunks_are_bounded_after_decode() {
        let big = vec![b'x'; MAX_LOG_CHUNK_BYTES + 1];
        let encoded = {
            use base64::{Engine, engine::general_purpose::STANDARD};
            STANDARD.encode(&big)
        };
        let body = format!(
            r#"{{"Event":{{"session":"s","epoch":1,"Log":{{"vertex":"v","chunk":"{encoded}","truncated":false}}}}}}"#
        );
        let mut frame = (body.len() as u64).to_le_bytes().to_vec();
        frame.extend_from_slice(body.as_bytes());
        let result: Result<Frame<FromBridge>, _> = decode_frame(&frame);
        assert!(matches!(result, Err(ProtocolError::Malformed(_))));
    }

    #[test]
    fn negotiation_is_one_exact_version_pair() {
        let ok = FromBridge::NegotiateOk {
            protocol_version: PROTOCOL_VERSION,
            daemon_version: "v0.33.0".into(),
            capabilities: vec!["llb.v1".into()],
        };
        assert_eq!(negotiate(&ok).unwrap(), vec!["llb.v1".to_string()]);

        let old = FromBridge::NegotiateOk {
            protocol_version: PROTOCOL_VERSION - 1,
            daemon_version: "v0.32.0".into(),
            capabilities: vec![],
        };
        match negotiate(&old) {
            Err(ProtocolError::VersionMismatch(got, want)) => {
                assert_eq!((got, want), (PROTOCOL_VERSION - 1, PROTOCOL_VERSION));
            }
            other => panic!("expected a version mismatch refusal, got {other:?}"),
        }
    }

    #[test]
    fn digests_and_sessions_validate_their_shape() {
        assert_eq!(Digest::of(b"").as_str().len(), 64);
        assert!(Digest::try_from("XYZ".to_string()).is_err());
        assert!(Digest::try_from("A".repeat(64)).is_err());
        assert!(SessionId::new("").is_err());
        assert!(SessionId::new("../escape").is_err());
        assert!(SessionId::new("a".repeat(65)).is_err());
        assert!(SessionId::new("build_1-A").is_ok());
    }

    #[test]
    fn the_gate_fences_stale_duplicate_and_flooding_events() {
        let mut gate = EventGate::new(7);
        gate.log(7).unwrap();
        gate.observe(7).unwrap();
        assert_eq!(
            gate.log(6),
            Err(GateError::StaleEpoch(6, 7)),
            "a stale epoch cannot emit events"
        );
        assert_eq!(
            gate.observe(8),
            Err(GateError::FutureEpoch(8, 7)),
            "epochs never jump ahead"
        );

        gate.terminal(7, Terminal::Cancelled).unwrap();
        assert_eq!(gate.terminal_state(), Some(Terminal::Cancelled));
        assert_eq!(
            gate.terminal(7, Terminal::Cancelled),
            Err(GateError::AlreadyTerminal(Terminal::Cancelled)),
            "even the same terminal twice is a fenced duplicate"
        );
        assert_eq!(
            gate.log(7),
            Err(GateError::AlreadyTerminal(Terminal::Cancelled)),
            "cancellation fences acceptance immediately"
        );

        let mut flooding = EventGate::new(1);
        for _ in 0..EventGate::MAX_LOG_EVENTS {
            flooding
                .log(1)
                .expect("the budget admits exactly MAX_LOG_EVENTS chunks");
        }
        assert_eq!(
            flooding.log(1),
            Err(GateError::LogBudget(
                EventGate::MAX_LOG_EVENTS + 1,
                EventGate::MAX_LOG_EVENTS
            )),
            "the next chunk over the budget rejects instead of unbounded buffering"
        );
    }
}
