//! GENERATED by scripts/gen_frontend_embed.py — do not edit.
//! The frontend, vendored as string literals (0035 F6): crates.io
//! builds carry the full evaluator; the docker test gate diffs this
//! file against a fresh regeneration.

/// (path inside the materialized frontend dir, source) pairs.
#[rustfmt::skip]
pub static FRONTEND_FILES: &[(&str, &str)] = &[
    ("src/cli.ts", r#"/** Eval driver (0013 D2/D5): `deno run … src/cli.ts <repo> --inputs <path>`.
 *
 * Runs inside the core's sandbox (no env, no network, no subprocesses,
 * read-only within the repo + the inputs dir + the embedded frontend).
 * Imports the repo's host entrypoint, calls its `defineEnv` function
 * with the core-injected context, and prints the eval envelope on
 * stdout: {"ir": …, "diagnostics": [], "probe_requests": […]}.
 * Error diagnostics exit 1 (tracebacks are the frontend's domain; the
 * core passes stderr through untouched, 0005 §4).
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { core, coreUrl } from "./pin.ts";
import type { Env } from "./graph.ts";

function die(msg: string): never {
  console.error(`gripsack: ${msg}`);
  process.exit(1);
}

async function main(): Promise<void> {
  if (
    typeof core.parseInputs !== "function" ||
    typeof core.createProbeBuilder !== "function" ||
    typeof core.emitIr !== "function"
  ) {
    die(
      `the pinned @gripsack/core at ${coreUrl} predates the defineEnv frontend ` +
        `(0013) — update or remove the repo's node_modules/@gripsack/core pin`,
    );
  }

  const args = process.argv.slice(2);
  const repo = resolve(args[0] ?? ".");
  let inputsPath: string | undefined;
  for (let i = 1; i < args.length; i++) {
    if (args[i] === "--inputs" && args[i + 1] !== undefined) inputsPath = args[++i];
  }
  if (inputsPath === undefined) die("--inputs <path> is required (the core always passes it)");

  const inputs = core.parseInputs(readFileSync(inputsPath, "utf8"), inputsPath);
  // host entrypoint: selected by the core (hostname / [env]
  // default_host / --host), named in the inputs envelope
  const hostFile = join(repo, "hosts", `${inputs.host}.ts`);
  // existence is checked up front — deno's failure messages differ
  // across versions, so an import error must ALWAYS mean a real
  // defect in the host file (broken import, syntax error) and pass
  // through as a traceback, never masquerade as a missing host
  if (!existsSync(hostFile)) {
    // a hosts/ dir with no match must not silently yield an empty env
    // — every when(tags=[…]) module would silently drop (same rule as
    // the python frontend had, enterprise review)
    let existing: string[] = [];
    try {
      existing = readdirSync(join(repo, "hosts")).filter((f) => f.endsWith(".ts"));
    } catch {
      // no hosts dir at all
    }
    const have = existing.map((f) => f.replace(/\.ts$/, "")).join(", ");
    die(
      existing.length > 0
        ? `no hosts/${inputs.host}.ts (have: ${have}) — add the file or change the host selection`
        : `no hosts/${inputs.host}.ts and no hosts/ directory in ${repo} — add hosts/${inputs.host}.ts`,
    );
  }
  // plugin loading: the host file is runtime-selected by the repo —
  // a static import cannot exist here
  const hostMod = (await import(pathToFileURL(hostFile).href)) as { default?: unknown };

  const envFn = hostMod.default;
  if (typeof envFn !== "function") {
    die(
      `hosts/${inputs.host}.ts must default-export defineEnv((ctx) => ({ tags, modules })) ` +
        "(0013 D5)",
    );
  }

  const { probe, requests } = core.createProbeBuilder(inputs.probes);
  const env = (envFn as (ctx: unknown) => unknown)({
    facts: inputs.facts,
    tags: inputs.tags,
    probe,
    settings: inputs.settings,
  }) as Env;
  if (
    typeof env !== "object" || env === null || !Array.isArray(env.modules) ||
    (env.tags !== undefined && !Array.isArray(env.tags))
  ) {
    die(
      `hosts/${inputs.host}.ts must synchronously return { tags?, modules: [...] } ` +
        `(got ${env instanceof Promise ? "a promise — return the env directly" : typeof env})`,
    );
  }

  const tags = core.mergeTags(env.tags, inputs.tags);
  const payload = {
    ir: JSON.parse(core.emitIr(env, inputs.facts, tags)),
    diagnostics: [],
    probe_requests: requests,
  };
  process.stdout.write(JSON.stringify(payload) + "\n");
}

main().catch((e: unknown) => {
  // frontend tracebacks are the frontend's domain — the core passes
  // stderr through untouched (0005 §4)
  console.error(e);
  process.exit(1);
});
"#),
    ("src/conditions.ts", r#"/** Conditional logic over core-injected facts (0001 §5, 0013 D4).
 *  Pure functions: they take the fact view as an argument instead of
 *  reading a global — `when(cond, ctx)` inside a `defineEnv`
 *  function, where ctx is handed in. */

import type { HostFacts } from "./facts.ts";

/** What conditionals evaluate against. The eval context satisfies
 *  this structurally, so `when(cond, ctx)` and `hasTag(t, ctx)` work
 *  on the context directly. */
export interface FactView {
  facts: HostFacts;
  tags: string[];
}

export interface Condition {
  os?: string;
  arch?: string;
  /** `null` matches "undetectable". */
  libc?: string | null;
  tags?: string[];
  notTags?: string[];
}

/** Build a condition over host facts — evaluate directly:
 *  `when({ os: "linux" }, ctx) && module(...)`, or gate a whole entry
 *  on it. Falsy-drop in `defineEnv`'s modules array does the rest. */
export function when(cond: Condition, view: FactView): boolean {
  const f = view.facts;
  if (cond.os !== undefined && f.os !== cond.os) return false;
  if (cond.arch !== undefined && f.arch !== cond.arch) return false;
  if (cond.libc !== undefined && (f.libc ?? null) !== cond.libc) return false;
  if (cond.tags?.some((t) => !view.tags.includes(t))) return false;
  if (cond.notTags?.some((t) => view.tags.includes(t))) return false;
  return true;
}

/** True when the merged tag set contains `tag`. */
export function hasTag(tag: string, view: FactView): boolean {
  return view.tags.includes(tag);
}
"#),
    ("src/deps.ts", r#"/** Module dependency edges (0001 §3.1). */

export type Edge = "runtime" | "build";

export interface Dependency {
  module: string;
  edge: Edge;
}

/** `edge: "build"` = ephemeral, build-only. */
export const dep = (module: string, edge: Edge = "runtime"): Dependency => ({
  module,
  edge,
});
"#),
    ("src/entries.ts", r#"/** Deployment destinations with ownership modes (0001 §3.7). */

export type Ownership = "owned" | "tracked_copy" | "merge" | "template";

export interface Dest {
  to: string;
  mode: Ownership;
  /** Template variables (mode "template" only) — `{{ name }}` in the
      payload is substituted at deploy time. */
  vars?: Record<string, string>;
  /** Comment prefix for the managed block (mode "merge" only);
      undefined infers it from the destination extension. */
  marker?: string;
}

/** Store-owned, read-only; edits go through the module. */
export const symlink = (to: string): Dest => ({ to, mode: "owned" });
/** Copied from the store; drift detected on next apply. */
export const trackedCopy = (to: string): Dest => ({ to, mode: "tracked_copy" });
/** Managed block merged into a file other tools also write. */
export const merge = (to: string, marker?: string): Dest => ({
  to,
  mode: "merge",
  ...(marker !== undefined ? { marker } : {}),
});
/** Rendered at deploy time from `{{ name }}` placeholders. */
export const template = (to: string, vars?: Record<string, string>): Dest => ({
  to,
  mode: "template",
  ...(vars ? { vars } : {}),
});
"#),
    ("src/facts.ts", r#"/** Host facts — core-injected, pure data (0013 D4).
 *
 * The frontend never detects anything: one detector (the Rust core,
 * via the inputs envelope), one frontend. `os`/`arch` are the core's
 * `std::env::consts` values, `libc` is parsed there (`glibc-<ver>`,
 * `musl`, `darwin`). */

export interface HostFacts {
  os: string;
  arch: string;
  /** e.g. "glibc-2.36", "musl", "darwin" — binary asset selection
   *  depends on it; null when undetectable. */
  libc: string | null;
  hostname: string;
}
"#),
    ("src/fetch.ts", r#"/** Typed fetchers (0001 §3.1, 0002 §2). */

export type Fetch =
  | { kind: "github_release"; repo: string; asset: string; version?: string; sha256?: string; base_url?: string }
  | { kind: "tarball"; url: string; sha256?: string }
  | { kind: "git"; url: string; rev?: string }
  | { kind: "file"; path: string }
  | { kind: "plugin"; name: string; args?: Record<string, unknown> }
  | { kind: "brew"; formula: string; version?: string; sha256?: string }
  | { kind: "pixi"; package: string; version?: string; sha256?: string };

/**
 * GitHub release fetcher. `asset` patterns accept `{version}` (the
 * tag, either v-form) and the platform placeholders (0016 §D1):
 * `{system}` (x86_64-linux, flake-style), `{target}` (the rust
 * triple, musl for linux), `{arch}` (x86_64|aarch64), `{arch.go}`
 * (amd64|arm64), `{os}` (linux|darwin) — expanded by the core from the
 * machine's facts, so one spec serves every platform.
 */
export function githubRelease(spec: {
  repo: string;
  asset: string;
  version?: string;
  sha256?: string;
  base_url?: string;
}): Fetch {
  return { kind: "github_release", ...spec };
}

/** Direct tarball/zip URL; accepts the same platform placeholders as
 *  githubRelease (0016 §D1). */
export function tarball(url: string, sha256?: string): Fetch {
  return sha256 === undefined
    ? { kind: "tarball", url }
    : { kind: "tarball", url, sha256 };
}

export function git(url: string, rev?: string): Fetch {
  // rev absent = float: the core pins the default branch's HEAD into
  // the lockfile at resolve time; `grip update` moves it (0016 §D2)
  return rev === undefined
    ? { kind: "git", url }
    : { kind: "git", url, rev };
}

export function fileFetch(path: string): Fetch {
  return { kind: "file", path };
}

/** A fetcher plugin transport (0002 §4) — `gripfetch-<name>`. */
export function pluginFetch(name: string, args?: Record<string, unknown>): Fetch {
  return args === undefined
    ? { kind: "plugin", name }
    : { kind: "plugin", name, args };
}

/** A Homebrew bottle — resolved from the formula JSON, so the pin
 *  needs no download at update time. `version` is a tripwire: a
 * mismatch fails at resolve (`grip update` to move), never a range. */
export function brew(formula: string, version?: string): Fetch {
  return version === undefined
    ? { kind: "brew", formula }
    : { kind: "brew", formula, version };
}

/** A conda package via pixi, isolated PIXI_HOME, harvested to store. */
export function pixi(pkg: string, version?: string): Fetch {
  return version === undefined
    ? { kind: "pixi", package: pkg }
    : { kind: "pixi", package: pkg, version };
}
"#),
    ("src/graph.ts", r#"/** The environment contract (0013 D5): `Inputs → Environment` as a
 *  function. No global registry, no import-order magic — the host
 *  entrypoint RETURNS its modules, the driver turns that value into
 *  IR (JSON). */

import type { HostFacts } from "./facts.ts";
import type { FactView } from "./conditions.ts";
import type { IrModule, ModuleValue } from "./module.ts";
import type { ProbeBuilder } from "./probe.ts";
import { declaredResources } from "./resources.ts";

export const IR_VERSION = 1;

/** The context a `defineEnv` function receives (0013 D5/D6): every
 *  host observation arrives here — facts and tags core-injected,
 *  probes symbolic, settings reserved. */
export interface EnvContext extends FactView {
  facts: HostFacts;
  tags: string[];
  probe: ProbeBuilder;
  settings: Record<string, unknown>;
}

/** A host environment: the entrypoint's tags plus its module values.
 *  Falsy `modules` entries drop out — `ctx.facts.os === "linux" &&
 *  steam` is the conditional style. */
export interface Env {
  tags?: string[];
  modules: ReadonlyArray<ModuleValue | false | null | undefined>;
}

export type EnvFn = (ctx: EnvContext) => Env;

/**
 * Declare a host entrypoint:
 *
 * ```ts
 * // hosts/laptop.ts
 * import { defineEnv } from "@gripsack/core";
 * import { helix } from "../modules/helix.js";
 *
 * export default defineEnv((ctx) => ({
 *   tags: ["gui", "work"],
 *   modules: [
 *     helix,
 *     ctx.facts.os === "linux" && steam,
 *     ctx.probe.executable("nvidia-smi") && cuda,
 *   ],
 * }));
 * ```
 *
 * The function runs inside the sandboxed eval with the core-injected
 * context and must return the environment synchronously. Identity —
 * the marker the driver checks for; the API anchor is the function
 * itself.
 */
export function defineEnv(fn: EnvFn): EnvFn {
  return fn;
}

/** Entrypoint tags ∪ CLI tags, order-preserving, deduplicated. The
 *  result is what lands in `ir.host.tags` and what a re-run's
 *  `ctx.tags` will contain (the core feeds the union back). */
export function mergeTags(envTags: string[] | undefined, cliTags: string[]): string[] {
  return [...(envTags ?? []), ...cliTags].filter((t, i, all) => all.indexOf(t) === i);
}

/** Serialize a returned environment as IR JSON. Duplicate module
 *  names throw with both declaration sites; stray objects throw with
 *  what they are. Key order is part of the contract (golden corpus):
 *  `ir_version, host, modules[, resources]`, host keys
 *  `os, arch, tags[, libc]` — hostname never crosses into the IR. */
export function emitIr(env: Env, facts: HostFacts, tags: string[]): string {
  const resources = declaredResources();
  const modules: Record<string, IrModule> = {};
  for (const m of env.modules ?? []) {
    if (!m) continue;
    if (typeof m !== "object" || m.__gripsack !== "module") {
      throw new Error(
        `env.modules entries must be module() values — got ${JSON.stringify(
          Array.isArray(m) ? "an array" : typeof m,
        )}`,
      );
    }
    const prev = modules[m.name];
    if (prev) {
      const where = prev.span ? ` (first declared at ${prev.span.file}:${prev.span.line})` : "";
      throw new Error(`duplicate module '${m.name}'${where}`);
    }
    modules[m.name] = m.ir;
  }
  const ir: Record<string, unknown> = {
    ir_version: IR_VERSION,
    host: {
      os: facts.os,
      arch: facts.arch,
      tags,
      ...(facts.libc !== null ? { libc: facts.libc } : {}),
    },
    modules,
  };
  if (resources.length > 0) ir.resources = resources;
  return JSON.stringify(ir, null, 2);
}
"#),
    ("src/index.ts", r#"/**
 * gripsack typescript frontend — typed module DSL, emits IR.
 *
 * A host is a function (0013 D5): `hosts/<name>.ts` default-exports
 * `defineEnv((ctx) => ({ tags?, modules }))`, evaluated inside a
 * sandboxed, provisioned Deno with every host observation injected
 * through the inputs envelope. The core never executes this code; it
 * only reads the IR.
 *
 * Spans (0004 §2): `module()` captures the caller's file:line:col from
 * the V8 stack so core errors point back at the user's source.
 */

export { dep } from "./deps.ts";
export type { Dependency, Edge } from "./deps.ts";
export { merge, symlink, template, trackedCopy } from "./entries.ts";
export type { Dest, Ownership } from "./entries.ts";
export type { HostFacts } from "./facts.ts";
export { brew, fileFetch, git, githubRelease, pixi, pluginFetch, tarball } from "./fetch.ts";
export type { Fetch } from "./fetch.ts";
export { hasTag, when } from "./conditions.ts";
export type { Condition, FactView } from "./conditions.ts";
export { defineEnv, emitIr, IR_VERSION, mergeTags } from "./graph.ts";
export type { Env, EnvContext, EnvFn } from "./graph.ts";
export { tree } from "./tree.ts";
export { module } from "./module.ts";
export type { IrEntry, IrModule, ModuleSpec, ModuleValue, Span } from "./module.ts";
export { customHook, desktopEntry, fonts, service } from "./intents.ts";
export type { Intent, Trigger } from "./intents.ts";
export { parseInputs } from "./inputs.ts";
export type { Inputs } from "./inputs.ts";
export { createProbeBuilder } from "./probe.ts";
export type { ProbeBuilder, ProbeKind, ProbeRequest } from "./probe.ts";
export { CORE_RESOURCES, clearResources, resource } from "./resources.ts";
export type { Resource } from "./resources.ts";
export { buildStep, configStep, fetchStep, installStep, runStep, shellStep, step } from "./steps.ts";
export type { Phase, Step, StepAction, StepOpts } from "./steps.ts";
export { verifyBinary, verifyDeployed, verifyFile, verifyShell } from "./verify.ts";
export type { Verify } from "./verify.ts";
"#),
    ("src/inputs.ts", r#"/** The inputs envelope (0013 D4): the core's JSON document handed to
 *  the frontend as `--inputs <path>` — the ONLY channel host
 *  observations arrive through. Not argv (world-visible), not env
 *  (leaks to children). */

import type { HostFacts } from "./facts.ts";

/** The eval inputs, version 1. */
export interface Inputs {
  /** Host entrypoint name — selects `hosts/<host>.ts`. */
  host: string;
  facts: HostFacts;
  /** CLI `--tags` merged with whatever the core already knows; the
   *  entrypoint's own tags are unioned in at emit (`mergeTags`). */
  tags: string[];
  /** Bound probe results, keyed `"<kind>:<arg>"`; empty in stage 1. */
  probes: Record<string, boolean>;
  settings: Record<string, unknown>;
}

const VERSION = 1;

function asRecord(v: unknown, where: string): Record<string, unknown> {
  if (v === undefined || v === null) return {};
  if (typeof v !== "object" || Array.isArray(v)) {
    throw new Error(`inputs: '${where}' must be an object`);
  }
  return v as Record<string, unknown>;
}

function asString(v: unknown, where: string): string {
  if (typeof v !== "string") throw new Error(`inputs: '${where}' must be a string`);
  return v;
}

/**
 * Parse + validate an inputs document. `source` names the file in
 * errors. Throws on anything structurally wrong — a malformed
 * envelope is a core/frontend version skew, not a user error, so it
 * must never silently degrade.
 */
export function parseInputs(text: string, source = "inputs"): Inputs {
  let doc: unknown;
  try {
    doc = JSON.parse(text);
  } catch (e) {
    throw new Error(`${source}: not valid JSON (${(e as Error).message})`);
  }
  const root = asRecord(doc, source);
  const version = root["version"];
  if (version !== VERSION) {
    throw new Error(
      `${source}: unsupported inputs version ${String(version)} (this frontend speaks ${VERSION})`,
    );
  }
  const host = asString(root["host"], "host");
  if (host === "") throw new Error(`${source}: 'host' must not be empty`);

  const factsRec = asRecord(root["facts"], "facts");
  const libc = factsRec["libc"];
  if (libc !== undefined && libc !== null && typeof libc !== "string") {
    throw new Error(`${source}: 'facts.libc' must be a string or null`);
  }
  const facts: HostFacts = {
    os: asString(factsRec["os"], "facts.os"),
    arch: asString(factsRec["arch"], "facts.arch"),
    libc: (libc as string | null | undefined) ?? null,
    hostname: asString(factsRec["hostname"], "facts.hostname"),
  };

  const tagsRaw = root["tags"] ?? [];
  if (!Array.isArray(tagsRaw) || tagsRaw.some((t) => typeof t !== "string")) {
    throw new Error(`${source}: 'tags' must be an array of strings`);
  }

  const probesRec = asRecord(root["probes"], "probes");
  const probes: Record<string, boolean> = {};
  for (const [k, v] of Object.entries(probesRec)) {
    if (typeof v !== "boolean") {
      throw new Error(`${source}: probes['${k}'] must be a boolean`);
    }
    probes[k] = v;
  }

  return {
    host,
    facts,
    tags: [...(tagsRaw as string[])],
    probes,
    settings: asRecord(root["settings"], "settings") as Record<string, unknown>,
  };
}
"#),
    ("src/intents.ts", r#"/** Activation intents — declared, translated by adapters (0001 §3.8). */

export type Trigger = "post_link" | "post_activate" | "on_remove";

export type Intent =
  | { kind: "service"; trigger: Trigger; name: string; user: boolean }
  | { kind: "fonts"; trigger: Trigger }
  | { kind: "desktop_entry"; trigger: Trigger }
  | { kind: "custom_shell"; trigger: Trigger; script: string };

export const service = (
  name: string,
  user = true,
  trigger: Trigger = "post_activate",
): Intent => ({ kind: "service", trigger, name, user });

export const fonts = (trigger: Trigger = "post_link"): Intent => ({
  kind: "fonts",
  trigger,
});

export const desktopEntry = (trigger: Trigger = "post_link"): Intent => ({
  kind: "desktop_entry",
  trigger,
});

/** Escape hatch — flagged, shown by `plan`.
 *
 * Activation intents are durable (plan/0032): a crash around the flip
 * re-runs them on the next `apply`. Write hooks IDEMPOTENT — they may
 * run more than once across a crash, and they are never silently
 * skipped. */
export const customHook = (script: string, trigger: Trigger = "post_activate"): Intent => ({
  kind: "custom_shell",
  trigger,
  script,
});
"#),
    ("src/module.ts", r#"/** Module declaration and span capture (0004 §2). `module()` is a
 * pure constructor (0013 D5): it builds and returns a
 * {@link ModuleValue}; nothing is registered anywhere. The host
 * entrypoint returns the values from `defineEnv`, and the driver
 * turns that environment into IR. */

import type { Dependency } from "./deps.ts";
import type { Dest, Ownership } from "./entries.ts";
import type { Fetch } from "./fetch.ts";
import type { Intent } from "./intents.ts";
import type { Step } from "./steps.ts";
import type { Verify } from "./verify.ts";

export interface Span {
  file: string;
  line: number;
  col?: number;
}

export interface ModuleSpec {
  /** Optional for dotfiles-only modules (0006 §2 level 1). Mutually
   *  exclusive with `steps` (0007 §1). */
  fetch?: Fetch;
  build?: { kind: "none" } | { kind: "custom_shell"; script: string };
  install?: Record<string, Dest>;
  config?: Record<string, Dest>;
  depends?: Dependency[];
  activate?: Intent[];
  /** Explicit pipeline control (0007). */
  steps?: Step[];
  /** Module-level smoke contract, run pre-flip (0007 §verify). */
  verify?: Verify;
  /** Retry default for this module's steps (0007 §retries). */
  retries?: number;
  /** Registered linter for this module's config payloads (0011) —
      the core drives it (0012). */
  lint?: string;
  /** Environment contributions exported to the shell profile at
      activation (0001 §3.10) — `{"VAR": "value", "PATH+": "{store}/bin"}`;
      a trailing `+` prepends to a list var. */
  env?: Record<string, string>;
}

export interface IrEntry {
  from: string;
  to: string;
  mode: Ownership;
  vars?: Record<string, string>;
  marker?: string;
}

export interface IrEnvVar {
  name: string;
  op: "set" | "prepend";
  value: string;
}

export interface IrModule {
  fetch?: Fetch;
  build?: ModuleSpec["build"];
  install?: IrEntry[];
  config?: IrEntry[];
  depends?: Dependency[];
  activate?: Intent[];
  steps?: Step[];
  verify?: Verify;
  retries?: number;
  lint?: string;
  env?: IrEnvVar[];
  span?: Span;
}

/** A constructed module — the value `module()` returns and
 * `defineEnv` environments carry. The brand distinguishes real
 * module values from stray objects in `env.modules` (a plain field,
 * deliberately: a repo's own pinned `@gripsack/core` install and the
 * embedded copy must agree on it). */
export interface ModuleValue {
  /** @internal */
  readonly __gripsack: "module";
  name: string;
  ir: IrModule;
}
/**
 * Declare a module from declarative fields (data style) and return
 * it — the host entrypoint puts the value into `defineEnv`'s
 * `modules` array; falsy entries (a condition that didn't hold)
 * simply drop out.
 *
 * For reuse, prefer a factory function over any framework — values
 * compose:
 *
 * @example
 * ```ts
 * function langServer(name: string, repo: string) {
 *   return module(name, {
 *     fetch: githubRelease({ repo, asset: `${name}-{version}.tar.gz` }),
 *     install: { [`bin/${name}`]: symlink(`~/.local/bin/${name}`) },
 *   });
 * }
 * ```
 */
export function module(name: string, spec: ModuleSpec): ModuleValue {
  // strict authoring boundary (0035 F3): the CLI runs this without a
  // type-checker — a typo'd field must not silently lower to an empty
  // desired state (a `confg:` became a prune). Runtime rejection is
  // the backstop for JS callers, casts, and generated objects.
  const KNOWN = new Set([
    "fetch", "build", "install", "config", "depends", "activate",
    "steps", "verify", "retries", "lint", "env",
  ]);
  const editDistance = (a: string, b: string): number => {
    let prev = Array.from({ length: b.length + 1 }, (_, j) => j);
    for (let i = 1; i <= a.length; i++) {
      const cur: number[] = [i];
      const prevRow: number[] = prev;
      for (let j = 1; j <= b.length; j++) {
        cur[j] = Math.min(
          prevRow[j]! + 1,
          cur[j - 1]! + 1,
          prevRow[j - 1]! + (a[i - 1] === b[j - 1] ? 0 : 1),
        );
      }
      prev = cur;
    }
    return prev[b.length]!;
  };
  for (const key of Object.keys(spec)) {
    if (!KNOWN.has(key)) {
      const closest = [...KNOWN]
        .map((k) => [k, editDistance(key, k)] as const)
        .filter(([, d]) => d <= 2)
        .sort((a, b) => a[1] - b[1])[0];
      throw new Error(
        `module("${name}"): unknown field "${key}"` +
          (closest ? ` — did you mean "${closest[0]}"?` : "") +
          ` (known: ${[...KNOWN].join(", ")})`,
      );
    }
  }
  const ir: IrModule = {};
  if (spec.fetch) ir.fetch = spec.fetch;
  if (spec.build) ir.build = spec.build;
  const entries = (rec?: Record<string, Dest>): IrEntry[] | undefined =>
    rec && Object.keys(rec).length > 0
      ? Object.entries(rec).map(([from, d]) => ({
          from,
          to: d.to,
          mode: d.mode,
          ...(d.vars ? { vars: d.vars } : {}),
          ...(d.marker !== undefined ? { marker: d.marker } : {}),
        }))
      : undefined;
  const install = entries(spec.install);
  if (install) ir.install = install;
  const config = entries(spec.config);
  if (config) ir.config = config;
  if (spec.depends?.length) ir.depends = spec.depends;
  if (spec.activate?.length) ir.activate = spec.activate;
  if (spec.steps?.length) ir.steps = spec.steps;
  if (spec.verify) ir.verify = spec.verify;
  if (spec.retries !== undefined) ir.retries = spec.retries;
  if (spec.lint !== undefined) ir.lint = spec.lint;
  if (spec.env !== undefined) {
    ir.env = Object.entries(spec.env).map(([name, value]) =>
      name.endsWith("+")
        ? { name: name.slice(0, -1), op: "prepend" as const, value }
        : { name, op: "set" as const, value },
    );
  }
  const span = callerSpan();
  if (span) ir.span = span;
  return { __gripsack: "module", name, ir };
}

/** @internal Capture the first stack frame outside the package (V8:
 *  file:line:col) — a helper wrapper in user code must never steal
 *  the span. Shared with the probe builder (0013 D6). */
export function callerSpan(): Span | undefined {
  const pkgDir = new URL(".", import.meta.url).pathname;
  const stack = new Error().stack;
  if (!stack) return undefined;
  for (const line of stack.split("\n").slice(1)) {
    const m = line.match(/\(?([^()\s]+):(\d+):(\d+)\)?$/);
    if (m && m[1] && !m[1].replace(/^file:\/\//, "").startsWith(pkgDir)) {
      const file = m[1].replace(/^file:\/\//, "");
      return { file, line: Number(m[2]), col: Number(m[3]) };
    }
  }
  return undefined;
}
"#),
    ("src/pin.ts", r#"/** The deliberate-pin shim (0013 D2/D3) — the deno.json import-map
 *  target for bare `@gripsack/core` imports.
 *
 * The sandboxed driver (`deno run --no-remote --cached-only --no-lock
 * --allow-read=…`) resolves the repo host entrypoint's `import … from
 * "@gripsack/core"` through the import map to THIS file, which then
 * applies the pin rule exactly once for the whole eval: the repo's own
 * `node_modules/@gripsack/core` install wins when it shadows this
 * embedded copy; the package next to this file is the fallback. The
 * driver (cli.ts) imports the same instance, so module values,
 * resource declarations, and probes always share one registry no
 * matter which copy won.
 *
 * The re-export list mirrors index.ts exactly — kept honest by the
 * pin parity test. */

import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type * as Index from "./index.ts";

/** The winning @gripsack/core URL, resolved from the repo's
 *  perspective — `repo` is the driver's first argument. */
export function resolveCoreUrl(repo: string, self: string): string {
  // the pin lives at the repo root, NOWHERE else: the eval sandbox
  // allows reading <repo> only, so a hoisted parent node_modules is
  // both unreadable and unimportable — and createRequire().resolve is
  // ambient-scope-sensitive under deno besides (it can see the
  // frontend's own package from a dev-checkout cwd)
  const pkgDir = join(resolve(repo), "node_modules", "@gripsack", "core");
  const pkgFile = join(pkgDir, "package.json");
  if (existsSync(pkgFile)) {
    const pkg = JSON.parse(readFileSync(pkgFile, "utf8")) as {
      main?: string;
      exports?: Record<string, unknown>;
    };
    const dot = pkg.exports?.["."];
    const entry = typeof dot === "string"
      ? dot
      : (dot as { import?: unknown; default?: unknown } | undefined);
    const rel =
      (typeof entry === "string" ? entry : undefined) ??
      (entry && typeof entry === "object"
        ? ((entry.import ?? entry.default) as string | undefined)
        : undefined) ??
      pkg.main ??
      "index.js";
    return pathToFileURL(join(pkgDir, rel)).href;
  }
  // the sibling entry of THIS file: index.ts in the embedded tree,
  // index.js in a tsc-built dist (string literals are not rewritten
  // by rewriteRelativeImportExtensions — only import specifiers are)
  return new URL(`./index${self.slice(-3)}`, self).href;
}

export const coreUrl = resolveCoreUrl(resolve(process.argv[2] ?? "."), import.meta.url);

// plugin loading: which package instance wins is decided at runtime
// (the repo's pin vs this embedded copy) — a static import would
// always load the embedded one and defeat the pin rule
let api: typeof Index;
try {
  api = await import(coreUrl) as typeof Index;
} catch (e) {
  console.error(
    `gripsack: the pinned @gripsack/core at ${coreUrl} failed to load: ` +
      `${(e as Error).message} — fix or remove the pin (node_modules/@gripsack/core)`,
  );
  process.exit(1);
}

/** The winning package instance — the driver and every host module
 *  share it. */
export const core = api;

export const dep = api.dep;
export const merge = api.merge;
export const symlink = api.symlink;
export const template = api.template;
export const trackedCopy = api.trackedCopy;
export const brew = api.brew;
export const fileFetch = api.fileFetch;
export const git = api.git;
export const githubRelease = api.githubRelease;
export const pixi = api.pixi;
export const pluginFetch = api.pluginFetch;
export const tarball = api.tarball;
export const hasTag = api.hasTag;
export const when = api.when;
export const defineEnv = api.defineEnv;
export const emitIr = api.emitIr;
export const IR_VERSION = api.IR_VERSION;
export const mergeTags = api.mergeTags;
export const tree = api.tree;
export const module = api.module;
export const customHook = api.customHook;
export const desktopEntry = api.desktopEntry;
export const fonts = api.fonts;
export const service = api.service;
export const parseInputs = api.parseInputs;
export const createProbeBuilder = api.createProbeBuilder;
export const CORE_RESOURCES = api.CORE_RESOURCES;
export const clearResources = api.clearResources;
export const resource = api.resource;
export const buildStep = api.buildStep;
export const configStep = api.configStep;
export const fetchStep = api.fetchStep;
export const installStep = api.installStep;
export const runStep = api.runStep;
export const shellStep = api.shellStep;
export const step = api.step;
export const verifyBinary = api.verifyBinary;
export const verifyDeployed = api.verifyDeployed;
export const verifyFile = api.verifyFile;
export const verifyShell = api.verifyShell;

export type {
  Condition,
  Dependency,
  Dest,
  Edge,
  Env,
  EnvContext,
  EnvFn,
  FactView,
  Fetch,
  HostFacts,
  Intent,
  Inputs,
  IrEntry,
  IrModule,
  ModuleSpec,
  ModuleValue,
  Ownership,
  Phase,
  ProbeBuilder,
  ProbeKind,
  ProbeRequest,
  Resource,
  Span,
  Step,
  StepAction,
  StepOpts,
  Trigger,
  Verify,
} from "./index.ts";
"#),
    ("src/probe.ts", r#"/** Symbolic probes (0013 D6): the sandbox cannot run effects (no
 *  `--allow-run`, no filesystem beyond the repo), so a probe call is
 *  always a REQUEST — recorded into the eval envelope for the core to
 *  bind, returning the bound value from the inputs (absent → false).
 *  Two-stage eval: stage 1 requests, the core evaluates the closed
 *  probe enum, stage 2 re-runs with `inputs.probes` populated. */

import { callerSpan } from "./module.ts";
import type { Span } from "./module.ts";

export type ProbeKind = "executable" | "file_exists";

/** A probe the core must bind before the next eval round. `name` is
 *  the executable name (PATH lookup) or the absolute file path. */
export interface ProbeRequest {
  kind: ProbeKind;
  name: string;
  span?: Span;
}

/** What `defineEnv` receives via `ctx.probe`.
 *
 * Probe a STABLE reference, never the tool's own installed presence:
 * `!probe.executable("node") && nodeModule` oscillates — installing
 * the tool makes the next eval drop the module. Probe the specific
 * system path you must not overwrite instead
 * (`probe.file_exists("/opt/vendor/bin/node")`). */
export interface ProbeBuilder {
  /** Is `<name>` an executable on PATH? */
  executable(name: string): boolean;
  /** Does the absolute `<path>` exist? */
  file_exists(path: string): boolean;
}

/** Collect requests while handing out bound answers. The driver
 *  emits `requests` in the envelope; an entry appears only when the
 *  probe is UNBOUND — a bound probe (even `false`) re-requests
 *  nothing, which is what makes two-stage eval reach a fixpoint. */
export function createProbeBuilder(
  bound: Record<string, boolean>,
): { probe: ProbeBuilder; requests: ProbeRequest[] } {
  const requests: ProbeRequest[] = [];
  const seen = new Set<string>();
  const ask = (kind: ProbeKind, name: string): boolean => {
    if (name === "") throw new Error(`probe.${kind}: name must not be empty`);
    const key = `${kind}:${name}`;
    if (!(key in bound) && !seen.has(key)) {
      seen.add(key);
      const span = callerSpan();
      requests.push(span ? { kind, name, span } : { kind, name });
    }
    return bound[key] ?? false;
  };
  return {
    probe: {
      executable: (name) => ask("executable", name),
      file_exists: (path) => ask("file_exists", path),
    },
    requests,
  };
}
"#),
    ("src/resources.ts", r#"/**
 * Declared resources — closing the namespace so typos are errors (0007 §4).
 *
 * Resources are named, host-global mutexes (or pools) that steps acquire
 * before running. The core has built-ins for known contention domains
 * (`network`, `pixi-lock`, `cargo-lock`); anything else must be declared
 * in your env repo.
 *
 * @example
 * ```ts
 * import { resource, step } from "@gripsack/core";
 *
 * const PIXI = resource("pixi.lock");
 * step("sync", { kind: "custom_shell", script: "pixi install" },
 *      { resources: ["pixi.lock"] });
 *
 * // typos throw at eval time, before the core ever sees your IR:
 * step("bad", { kind: "custom_shell", script: "true" },
 *      { resources: ["cargo.lokc"] }); // Error: unknown resource 'cargo.lokc'
 * ```
 */

/** Built-in contention domains the core knows how to serialize or
 *  throttle. Mirrors `KNOWN_RESOURCES` in `crates/gripsack-ir` — keep
 *  the two in sync (IR changes touch all sides). */
export const CORE_RESOURCES: ReadonlySet<string> = new Set([
  "network",
  "pixi-lock",
  "cargo-lock",
]);

/** A declared resource marker. Create with {@link resource}. */
export interface Resource {
  name: string;
}

const REGISTRY = new Map<string, Resource>();

/** Declare a resource and return its marker. */
export function resource(name: string): Resource {
  if (!name) throw new Error("resource name must not be empty");
  const r: Resource = { name };
  REGISTRY.set(name, r);
  return r;
}

/** All resources declared so far in this eval, sorted by name. */
export function declaredResources(): Resource[] {
  return [...REGISTRY.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** Drop all declared resources (test isolation). */
export function clearResources(): void {
  REGISTRY.clear();
}

/** @internal Throw if any ref is neither declared nor built-in. */
export function validateResourceRefs(refs: string[], owner: string): void {
  for (const ref of refs) {
    if (!REGISTRY.has(ref) && !CORE_RESOURCES.has(ref)) {
      const known = [...REGISTRY.keys(), ...CORE_RESOURCES].sort().join(", ");
      throw new Error(
        `unknown resource '${ref}' in ${owner} — declare it first with resource('${ref}'). Known: ${known}`,
      );
    }
  }
}
"#),
    ("src/steps.ts", r#"/**
 * Steps — the phase building blocks inside a module (0007).
 *
 * Most modules never write steps: the declarative fields are expanded
 * into the conventional pipeline by the core. Declare steps explicitly
 * for control — ordering, resource locks, retries, or a custom action.
 * `steps` and the declarative fields are mutually exclusive per module
 * (E103).
 */

import type { Dest } from "./entries.ts";
import type { Fetch } from "./fetch.ts";
import { validateResourceRefs } from "./resources.ts";
import type { Verify } from "./verify.ts";

export type Phase = "fetch" | "build" | "install" | "config" | "verify" | "activate" | "custom";

export type StepAction =
  | { kind: "fetch"; fetch: Fetch }
  | { kind: "build"; spec: Record<string, unknown> }
  | { kind: "install"; entries: unknown[] }
  | { kind: "config_deploy"; entries: unknown[] }
  | { kind: "run"; argv: string[]; env?: Record<string, string>; cwd?: string; outputs?: string[] }
  | { kind: "custom_shell"; script: string; outputs?: string[] };

export interface Step {
  id: string;
  action: StepAction;
  needs?: string[];
  resources?: string[];
  phase?: Phase;
  verify?: Verify;
  retries?: number;
}

export interface StepOpts {
  needs?: string[];
  resources?: string[];
  phase?: Phase;
  verify?: Verify;
  retries?: number;
}

export function step(id: string, action: StepAction, opts?: StepOpts): Step {
  validateResourceRefs(opts?.resources ?? [], `step '${id}'`);
  return { id, action, ...opts };
}

/** Primitives auto-declare their contention domain in the core
 *  (pixi → `pixi-lock`, …) — `resources` is for your own shared
 *  state (0007 §4). Fetch steps retry by default. */
export function fetchStep(fetch: Fetch, id = "fetch", opts?: StepOpts): Step {
  // runtime shape guard: an argument-order slip here would otherwise
  // surface as a byte-offset E000 from the core's deserializer, with
  // no module named — catch it at the call site instead (the eval
  // stack names file:line)
  if (typeof fetch !== "object" || fetch === null || typeof fetch.kind !== "string") {
    throw new TypeError(
      `fetchStep(fetch, id?) — the first argument must be a fetch spec from ` +
        `githubRelease()/tarball()/fileFetch()/git()/brew()/pixi()/pluginFetch(); ` +
        `got ${describe(fetch)} (arguments swapped?)`,
    );
  }
  validateResourceRefs(opts?.resources ?? [], `step '${id}'`);
  return { id, action: { kind: "fetch", fetch }, phase: "fetch", ...opts };
}

/** A one-phrase description of what actually arrived, for guard
 * messages — the type name is enough to spot a swapped argument. */
function describe(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "string") return `the string ${JSON.stringify(value)}`;
  if (Array.isArray(value)) return "an array";
  if (typeof value === "object") return "an object";
  return `a ${typeof value}`;
}

export function installStep(
  entries: Record<string, Dest>,
  id = "install",
  opts?: StepOpts,
): Step {
  if (typeof entries !== "object" || entries === null || Array.isArray(entries)) {
    throw new TypeError(
      `installStep(entries, id?) — the first argument must be the entries object ` +
        `{ "payload/path": symlink(…) }; got ${describe(entries)} (arguments swapped?)`,
    );
  }
  return {
    id,
    action: {
      kind: "install",
      entries: Object.entries(entries).map(([from, d]) => ({
        from,
        to: d.to,
        mode: d.mode,
        ...(d.vars ? { vars: d.vars } : {}),
        ...(d.marker !== undefined ? { marker: d.marker } : {}),
      })),
    } as StepAction,
    phase: "install",
    ...opts,
  };
}

export function buildStep(
  spec: Record<string, unknown>,
  id = "build",
  opts?: StepOpts,
): Step {
  return { id, action: { kind: "build", spec }, phase: "build", ...opts };
}

/** Deploy config files per their ownership modes (0001 §3.7). */
export function configStep(
  entries: Record<string, Dest>,
  id = "config",
  opts?: StepOpts,
): Step {
  if (typeof entries !== "object" || entries === null || Array.isArray(entries)) {
    throw new TypeError(
      `configStep(entries, id?) — the first argument must be the entries object ` +
        `{ "repo/path": trackedCopy(…) }; got ${describe(entries)} (arguments swapped?)`,
    );
  }
  return {
    id,
    action: {
      kind: "config_deploy",
      entries: Object.entries(entries).map(([from, d]) => ({
        from,
        to: d.to,
        mode: d.mode,
        ...(d.vars ? { vars: d.vars } : {}),
        ...(d.marker !== undefined ? { marker: d.marker } : {}),
      })),
    } as StepAction,
    phase: "config",
    ...opts,
  };
}

/** A structured action — the rung between primitives and shell
 *  (0007 §3): argv/env/cwd as data, no shell interpretation, declared
 *  `outputs` make it cacheable (0008 §4). */
export function runStep(
  argv: string[],
  id = "run",
  opts?: StepOpts & {
    env?: Record<string, string>;
    cwd?: string;
    outputs?: string[];
  },
): Step {
  const { env, cwd, outputs, ...rest } = opts ?? {};
  const action: StepAction = {
    kind: "run",
    argv,
    ...(env !== undefined ? { env } : {}),
    ...(cwd !== undefined ? { cwd } : {}),
    ...(outputs !== undefined ? { outputs } : {}),
  };
  return { id, action, phase: "custom", ...rest };
}

/** The last rung, not the default (0007 §3): declared, flagged in
 *  `plan`. Declared `outputs` restore caching/satisfaction (0008 §4);
 *  without them the step always runs. */
export function shellStep(
  script: string,
  id: string,
  opts?: StepOpts & { outputs?: string[] },
): Step {
  validateResourceRefs(opts?.resources ?? [], `step '${id}'`);
  const { outputs, ...rest } = opts ?? {};
  return {
    id,
    action: {
      kind: "custom_shell",
      script,
      ...(outputs !== undefined ? { outputs } : {}),
    },
    phase: rest.phase ?? "custom",
    ...rest,
  };
}
"#),
    ("src/tree.ts", r#"/** Tree entries — directory-shaped config deploys via eval-time
 *  expansion (the IR stays per-file). Adding or removing files in the
 *  directory is picked up at the next eval; files dropped from the
 *  tree are pruned at apply.
 *
 *  ```ts
 *  module("zed", { config: { ...tree("configs/zed", "~/.config/zed") } });
 *  ```
 */

import { readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import type { Dest, Ownership } from "./entries.ts";

export function tree(
  src: string,
  to: string,
  mode: Ownership = "tracked_copy",
): Record<string, Dest> {
  const entries: Record<string, Dest> = {};
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir).sort()) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) {
        walk(path);
      } else if (statSync(path).isFile()) {
        const rel = relative(src, path).split("\\").join("/");
        entries[`${src}/${rel}`] = { to: `${to}/${rel}`, mode };
      }
    }
  };
  walk(src);
  return entries;
}
"#),
    ("src/verify.ts", r#"/** Verify checks — smoke contracts, not a test framework (0007 §verify). */

export type Verify =
  | { kind: "binary_runs"; path: string; args?: string[] }
  | { kind: "file_exists"; path: string }
  | { kind: "shell"; script: string }
  | { kind: "file_deployed"; path: string };

/** A built binary runs (default sanity: `--version`-style). */
export function verifyBinary(path: string, args?: string[]): Verify {
  return args === undefined
    ? { kind: "binary_runs", path }
    : { kind: "binary_runs", path, args };
}

export function verifyFile(path: string): Verify {
  return { kind: "file_exists", path };
}

export function verifyShell(script: string): Verify {
  return { kind: "shell", script };
}

/** Check a deployed *destination* — for config-only modules, where
 *  payload-relative verifies don't apply. */
export function verifyDeployed(path: string): Verify {
  return { kind: "file_deployed", path };
}
"#),
    ("deno.json", r#"{
  "imports": {
    "@gripsack/core": "./src/pin.ts"
  },
  "tasks": {
    "test": "deno test --allow-read --allow-write --allow-run --allow-env test/"
  }
}
"#),
    ("package.json", r#"{
  "name": "@gripsack/core",
  "version": "0.21.0",
  "description": "gripsack typescript frontend \u2014 typed module DSL, emits IR",
  "license": "MIT",
  "type": "module",
  "main": "./dist/src/index.js",
  "types": "./dist/src/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/src/index.d.ts",
      "import": "./dist/src/index.js",
      "require": "./dist/src/index.js"
    }
  },
  "files": [
    "dist/src"
  ],
  "scripts": {
    "build": "tsc",
    "test": "deno task test"
  },
  "keywords": [
    "dotfiles",
    "package-manager",
    "environment"
  ],
  "homepage": "https://gripsack.dev",
  "repository": "https://github.com/gripsack-dev/gripsack",
  "engines": {
    "node": ">=18"
  },
  "devDependencies": {
    "@types/node": "^26",
    "typescript": "^7"
  }
}
"#),
];
