//! Exported env (0001 §3.10, reworked by 0025 §C): modules contribute
//! variables to the user's shell. The profile lives INSIDE the
//! generation — `generations/<N>/env/profile.sh` — rendered before
//! the flip on apply AND rollback, and sourced through
//! `$GRIPSACK_HOME/current/env/profile.sh`. The rc-side path is still
//! stable, but it resolves through the `current` symlink: the profile
//! activates with the generation, indivisibly. (The pre-0.22 stable
//! `env/profile.sh` had two asymmetric windows — new profile before
//! the flip on apply, stale profile after the flip on rollback.)

use gripsack_ir::EnvOp;
use gripsack_store as store;
use std::collections::BTreeMap;
use std::io;
use std::path::{Path, PathBuf};

/// The profile's content, pure (0027 §8): generation publication
/// writes it into staging. None when nothing is contributed — the
/// rc-side `[ -f ... ]` guard reads that as "nothing to export".
pub fn render_profile(modules: &BTreeMap<String, store::ModuleState>) -> Option<String> {
    render_lines(modules).map(|lines| lines.join("\n"))
}

/// Backfill a MISSING profile into an existing generation — pre-0.22
/// history only; a present profile is never rewritten (generations
/// are immutable, 0027 §8). Returns the path either way.
pub fn render_env_file(
    home: &Path,
    generation: u64,
    modules: &BTreeMap<String, store::ModuleState>,
) -> io::Result<PathBuf> {
    let rel = Path::new("generations")
        .join(generation.to_string())
        .join("env")
        .join("profile.sh");
    let path = home.join(&rel);
    // the legacy pre-0.22 location goes away either way
    let legacy = home.join("env");
    let _ = std::fs::remove_file(legacy.join("profile.sh"));
    let _ = std::fs::remove_dir(&legacy);
    if path.exists() {
        return Ok(path);
    }
    let cap = gripsack_fs::open_or_create(home)?;
    let Some(text) = render_profile(modules) else {
        return Ok(path); // no contributions: nothing to backfill
    };
    gripsack_fs::atomic_write(&cap, &rel, text.as_bytes())?;
    Ok(path)
}

fn render_lines(modules: &BTreeMap<String, store::ModuleState>) -> Option<Vec<String>> {
    let mut lines = vec![
        "# Generated by gripsack — regenerated at every activation.".to_string(),
        "# Source this from your shell rc: [ -f \"$XDG_DATA_HOME/gripsack/current/env/profile.sh\" ] && . \"$XDG_DATA_HOME/gripsack/current/env/profile.sh\"".to_string(),
    ];
    // (name, op, resolved value) — first occurrence wins on exact dupes
    let mut seen = std::collections::BTreeSet::new();
    let mut any = false;
    for state in modules.values() {
        for var in &state.env {
            // manifests are disk state: a name that is not a shell
            // identifier would inject into every shell that sources
            // this profile. sema rejects these at eval; this guard is
            // for the hand-edited manifest.
            if !is_identifier(&var.name) {
                // data up, rendering at the edge: lower crates never
                // print — this surfaces in the run log instead
                tracing::warn!(name = %var.name, "skipping env var with an invalid name");
                continue;
            }
            let resolved = var
                .value
                .replace("{store}", &state.store_path.to_string_lossy());
            if !seen.insert((&var.name, var.op, resolved.clone())) {
                continue;
            }
            any = true;
            let line = match var.op {
                EnvOp::Set => format!("export {}=\"{}\"", var.name, shell_quote(&resolved)),
                EnvOp::Prepend => format!(
                    "export {}=\"{}:${{{}}}\"",
                    var.name,
                    shell_quote(&resolved),
                    var.name
                ),
                EnvOp::Append => format!(
                    "export {}=\"${{{}}}:{}\"",
                    var.name,
                    var.name,
                    shell_quote(&resolved)
                ),
            };
            lines.push(line);
        }
    }
    if !any {
        return None;
    }
    Some(lines)
}

/// A shell-safe env var name: POSIX identifier rules. The value side
/// is quoted; the name side cannot be, so it is validated instead.
fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Escape backslash, quote, and backtick (the caller adds the double
/// quotes). `$` is left alone: values like "$HOME/bin" expand at
/// source time — that is a feature (0001 §3.10).
/// `$` stays live BY DESIGN ("$HOME/bin" expands at source time).
/// That deliberately also admits $(...) and ${...} — env values come
/// from the trusted, eval-gated repo, and the profile is documented
/// as sourced code (0030 §19). Backticks are escaped: no gripsack
/// feature needs them, and they're the legacy execution form.
fn shell_quote(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('`', "\\`")
}

#[cfg(test)]
mod tests {
    use super::*;
    use gripsack_ir::{EnvVar, Ownership};

    fn state(store: &str, env: Vec<EnvVar>) -> store::ModuleState {
        store::ModuleState {
            store_path: PathBuf::from(store),
            entries: vec![store::DeployedEntry {
                from: "a".into(),
                to: "~/.a".into(),
                mode: Ownership::Owned,
                vars: Default::default(),
                hash: "h".into(),
                prior: None,
                preserved_drift: false,
            }],
            env,
            tree256: None,
        }
    }

    fn var(name: &str, op: EnvOp, value: &str) -> EnvVar {
        EnvVar {
            name: name.into(),
            op,
            value: value.into(),
        }
    }

    #[test]
    fn renders_set_prepend_append_with_store_resolution() {
        let dir = tempfile::tempdir().unwrap();
        let mut modules = BTreeMap::new();
        modules.insert(
            "hx".to_string(),
            state(
                "/gs/store/abc-hx",
                vec![
                    var("EDITOR", EnvOp::Set, "hx"),
                    var("PATH", EnvOp::Prepend, "{store}/bin"),
                    var("MANPATH", EnvOp::Append, "{store}/man"),
                ],
            ),
        );
        let path = render_env_file(dir.path(), 1, &modules).unwrap();
        let out = std::fs::read_to_string(path).unwrap();
        assert!(out.contains("export EDITOR=\"hx\""), "{out}");
        assert!(
            out.contains("export PATH=\"/gs/store/abc-hx/bin:${PATH}\""),
            "{out}"
        );
        assert!(
            out.contains("export MANPATH=\"${MANPATH}:/gs/store/abc-hx/man\""),
            "{out}"
        );
    }

    #[test]
    fn empty_contributions_remove_the_file() {
        let dir = tempfile::tempdir().unwrap();
        let mut modules = BTreeMap::new();
        modules.insert(
            "hx".to_string(),
            state("/gs/store/abc-hx", vec![var("A", EnvOp::Set, "1")]),
        );
        render_env_file(dir.path(), 1, &modules).unwrap();
        // the profile is generation-local now (0025 §C)
        let path = dir.path().join("generations/1/env/profile.sh");
        assert!(path.exists());
        modules.insert("hx".to_string(), state("/gs/store/abc-hx", vec![]));
        // a generation with no contributions carries no profile
        render_env_file(dir.path(), 2, &modules).unwrap();
        assert!(!dir.path().join("generations/2/env/profile.sh").exists());
    }

    #[test]
    fn duplicate_contributions_render_once() {
        let dir = tempfile::tempdir().unwrap();
        let mut modules = BTreeMap::new();
        let s = state(
            "/gs/store/abc-hx",
            vec![var("PATH", EnvOp::Prepend, "{store}/bin")],
        );
        modules.insert("a".to_string(), s.clone());
        modules.insert("b".to_string(), s);
        let path = render_env_file(dir.path(), 1, &modules).unwrap();
        let out = std::fs::read_to_string(path).unwrap();
        assert_eq!(out.matches("abc-hx/bin").count(), 1, "{out}");
    }
}
