//! Exported env (0001 §3.10): modules contribute variables to the
//! user's shell. At every activation (and rollback) the engine
//! regenerates `$GRIPSACK_HOME/env/profile.sh` from the manifest —
//! the user sources it once from their rc file; after that the file
//! tracks the generation, not the rc.

use gripsack_ir::EnvOp;
use gripsack_store as store;
use std::collections::BTreeMap;
use std::io;
use std::path::{Path, PathBuf};

/// Regenerate the profile from the generation's manifest. A generation
/// with no contributions removes the file — stale exports never linger.
pub fn render_env_file(
    home: &Path,
    modules: &BTreeMap<String, store::ModuleState>,
) -> io::Result<PathBuf> {
    let path = home.join("env").join("profile.sh");
    let mut lines = vec![
        "# Generated by gripsack — regenerated at every activation.".to_string(),
        "# Source this from your shell rc: [ -f \"$XDG_DATA_HOME/gripsack/env/profile.sh\" ] && . \"$XDG_DATA_HOME/gripsack/env/profile.sh\"".to_string(),
    ];
    // (name, op, resolved value) — first occurrence wins on exact dupes
    let mut seen = std::collections::BTreeSet::new();
    let mut any = false;
    for state in modules.values() {
        for var in &state.env {
            let resolved = var
                .value
                .replace("{store}", &state.store_path.to_string_lossy());
            if !seen.insert((&var.name, var.op, resolved.clone())) {
                continue;
            }
            any = true;
            let line = match var.op {
                EnvOp::Set => format!("export {}=\"{}\"", var.name, shell_quote(&resolved)),
                EnvOp::Prepend => format!(
                    "export {}=\"{}:${{{}}}\"",
                    var.name,
                    shell_quote(&resolved),
                    var.name
                ),
                EnvOp::Append => format!(
                    "export {}=\"${{{}}}:{}\"",
                    var.name,
                    var.name,
                    shell_quote(&resolved)
                ),
            };
            lines.push(line);
        }
    }
    if !any {
        let _ = std::fs::remove_file(&path);
        return Ok(path);
    }
    store::atomic_write(&path, lines.join("\n").as_bytes())?;
    Ok(path)
}

/// Escape backslash, quote, and backtick (the caller adds the double
/// quotes). `$` is left alone: values like "$HOME/bin" expand at
/// source time — that is a feature (0001 §3.10).
fn shell_quote(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('`', "\\`")
}

#[cfg(test)]
mod tests {
    use super::*;
    use gripsack_ir::{EnvVar, Ownership};

    fn state(store: &str, env: Vec<EnvVar>) -> store::ModuleState {
        store::ModuleState {
            store_path: PathBuf::from(store),
            entries: vec![store::DeployedEntry {
                from: "a".into(),
                to: "~/.a".into(),
                mode: Ownership::Owned,
                vars: Default::default(),
                hash: "h".into(),
            }],
            env,
            tree256: None,
        }
    }

    fn var(name: &str, op: EnvOp, value: &str) -> EnvVar {
        EnvVar {
            name: name.into(),
            op,
            value: value.into(),
        }
    }

    #[test]
    fn renders_set_prepend_append_with_store_resolution() {
        let dir = tempfile::tempdir().unwrap();
        let mut modules = BTreeMap::new();
        modules.insert(
            "hx".to_string(),
            state(
                "/gs/store/abc-hx",
                vec![
                    var("EDITOR", EnvOp::Set, "hx"),
                    var("PATH", EnvOp::Prepend, "{store}/bin"),
                    var("MANPATH", EnvOp::Append, "{store}/man"),
                ],
            ),
        );
        let path = render_env_file(dir.path(), &modules).unwrap();
        let out = std::fs::read_to_string(path).unwrap();
        assert!(out.contains("export EDITOR=\"hx\""), "{out}");
        assert!(
            out.contains("export PATH=\"/gs/store/abc-hx/bin:${PATH}\""),
            "{out}"
        );
        assert!(
            out.contains("export MANPATH=\"${MANPATH}:/gs/store/abc-hx/man\""),
            "{out}"
        );
    }

    #[test]
    fn empty_contributions_remove_the_file() {
        let dir = tempfile::tempdir().unwrap();
        let mut modules = BTreeMap::new();
        modules.insert(
            "hx".to_string(),
            state("/gs/store/abc-hx", vec![var("A", EnvOp::Set, "1")]),
        );
        render_env_file(dir.path(), &modules).unwrap();
        let path = dir.path().join("env/profile.sh");
        assert!(path.exists());
        modules.insert("hx".to_string(), state("/gs/store/abc-hx", vec![]));
        render_env_file(dir.path(), &modules).unwrap();
        assert!(!path.exists());
    }

    #[test]
    fn duplicate_contributions_render_once() {
        let dir = tempfile::tempdir().unwrap();
        let mut modules = BTreeMap::new();
        let s = state(
            "/gs/store/abc-hx",
            vec![var("PATH", EnvOp::Prepend, "{store}/bin")],
        );
        modules.insert("a".to_string(), s.clone());
        modules.insert("b".to_string(), s);
        let path = render_env_file(dir.path(), &modules).unwrap();
        let out = std::fs::read_to_string(path).unwrap();
        assert_eq!(out.matches("abc-hx/bin").count(), 1, "{out}");
    }
}
