//! Exported env (0001 §3.10, reworked by 0025 §C): modules contribute
//! variables to the user's shell. The profile lives INSIDE the
//! generation — `generations/<N>/env/profile.sh` — rendered before
//! the flip on apply AND rollback, and sourced through
//! `$GRIPSACK_HOME/current/env/profile.sh`. The rc-side path is still
//! stable, but it resolves through the `current` symlink: the profile
//! activates with the generation, indivisibly. (The pre-0.22 stable
//! `env/profile.sh` had two asymmetric windows — new profile before
//! the flip on apply, stale profile after the flip on rollback.)

use gripsack_ir::EnvOp;
use gripsack_store as store;
use std::collections::BTreeMap;
use std::io;
use std::path::{Path, PathBuf};

/// The profile's content, pure (0027 §8): generation publication
/// writes it into staging. None when nothing is contributed — the
/// rc-side `[ -f ... ]` guard reads that as "nothing to export".
pub fn render_profile(modules: &BTreeMap<String, store::ModuleState>) -> Option<String> {
    render_lines(modules).map(|lines| lines.join("\n"))
}

/// Backfill a MISSING profile into an existing generation — pre-0.22
/// history only; a present profile is never rewritten (generations
/// are immutable, 0027 §8). Returns the path either way.
pub fn render_env_file(
    home: &Path,
    generation: store::GenerationId,
    modules: &BTreeMap<String, store::ModuleState>,
) -> io::Result<PathBuf> {
    let rel = Path::new("generations")
        .join(generation.to_string())
        .join("env")
        .join("profile.sh");
    let path = home.join(&rel);
    // the legacy pre-0.22 location goes away either way
    let legacy = home.join("env");
    let _ = std::fs::remove_file(legacy.join("profile.sh"));
    let _ = std::fs::remove_dir(&legacy);
    if path.exists() {
        return Ok(path);
    }
    let cap = gripsack_fs::open_or_create(home)?;
    let Some(text) = render_profile(modules) else {
        return Ok(path); // no contributions: nothing to backfill
    };
    gripsack_fs::atomic_write(&cap, &rel, text.as_bytes())?;
    Ok(path)
}

fn render_lines(modules: &BTreeMap<String, store::ModuleState>) -> Option<Vec<String>> {
    let mut lines = vec![
        "# Generated by gripsack — regenerated at every activation.".to_string(),
        "# Source this from your shell rc: [ -f \"$XDG_DATA_HOME/gripsack/current/env/profile.sh\" ] && . \"$XDG_DATA_HOME/gripsack/current/env/profile.sh\"".to_string(),
    ];
    // (name, op, resolved value) — first occurrence wins on exact dupes
    let mut seen = std::collections::BTreeSet::new();
    let mut any = false;
    for state in modules.values() {
        for var in &state.env {
            let name = var.name();
            let operation = var.operation();
            // manifests are disk state: a name that is not a shell
            // identifier would inject into every shell that sources
            // this profile. sema rejects these at eval; this guard is
            // for the hand-edited manifest.
            if !is_identifier(name) {
                // data up, rendering at the edge: lower crates never
                // print — this surfaces in the run log instead
                tracing::warn!(name, "skipping env var with an invalid name");
                continue;
            }
            let (resolved, literal): (std::borrow::Cow<'_, str>, bool) = match var {
                store::EnvironmentContribution::LegacyExpression(value) => (
                    value
                        .value
                        .replace("{store}", &state.store_path.to_string_lossy())
                        .into(),
                    false,
                ),
                store::EnvironmentContribution::Structured(
                    store::StructuredEnvironment::Literal { value, .. },
                ) => (value.as_str().into(), true),
                store::EnvironmentContribution::Structured(
                    store::StructuredEnvironment::StorePath { path, .. },
                ) => (
                    format!("{}/{path}", state.store_path.display()).into(),
                    true,
                ),
            };
            if !seen.insert((name, operation, literal, resolved.clone())) {
                continue;
            }
            any = true;
            let line = if literal {
                match operation {
                    EnvOp::Set => format!("export {name}={}", ShellLiteral(&resolved)),
                    EnvOp::Prepend => format!(
                        "export {name}={}${{{name}:+:}}\"${{{name}-}}\"",
                        ShellLiteral(&resolved)
                    ),
                    EnvOp::Append => format!(
                        "export {name}=\"${{{name}-}}\"${{{name}:+:}}{}",
                        ShellLiteral(&resolved)
                    ),
                }
            } else {
                // Historical generations retain expression expansion exactly.
                match operation {
                    EnvOp::Set => format!("export {name}=\"{}\"", shell_quote(&resolved)),
                    EnvOp::Prepend => {
                        format!("export {name}=\"{}:${{{name}}}\"", shell_quote(&resolved))
                    }
                    EnvOp::Append => {
                        format!("export {name}=\"${{{name}}}:{}\"", shell_quote(&resolved))
                    }
                }
            };
            lines.push(line);
        }
    }
    if !any {
        return None;
    }
    Some(lines)
}

/// A shell-safe env var name: POSIX identifier rules. The value side
/// is quoted; the name side cannot be, so it is validated instead.
pub(crate) fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Escape backslash, quote, and backtick (the caller adds the double
/// quotes). `$` is left alone: values like "$HOME/bin" expand at
/// source time — that is a feature (0001 §3.10).
/// `$` stays live BY DESIGN ("$HOME/bin" expands at source time).
/// That deliberately also admits $(...) and ${...} — env values come
/// from the trusted, eval-gated repo, and the profile is documented
/// as sourced code (0030 §19). Backticks are escaped: no gripsack
/// feature needs them, and they're the legacy execution form.
fn shell_quote(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('`', "\\`")
}

/// A shell word that can carry data but cannot grant expansion authority.
pub(crate) struct ShellLiteral<'a>(pub &'a str);
impl std::fmt::Display for ShellLiteral<'_> {
    fn fmt(&self, out: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        out.write_str("'")?;
        let mut parts = self.0.split('\'');
        if let Some(first) = parts.next() {
            out.write_str(first)?;
        }
        for part in parts {
            out.write_str("'\\''")?;
            out.write_str(part)?;
        }
        out.write_str("'")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gripsack_ir::{EnvVar, Ownership};

    fn state(store: &str, env: Vec<EnvVar>) -> store::ModuleState {
        store::ModuleState {
            store_path: PathBuf::from(store),
            build_only: false,
            intents: vec![],
            verified: None,
            entries: vec![store::DeployedEntry {
                from: "a".into(),
                to: "~/.a".into(),
                key: None,
                ownership: store::StoredOwnership::Legacy(Ownership::Owned),
                vars: Default::default(),
                hash: gripsack_store::hash::ManifestHash::from_raw("h".into()),
                file_mode: None,
                source_executable: None,
                prior: None,
                preserved_drift: false,
            }],
            env: env.into_iter().map(Into::into).collect(),
            tree256: None,
            build_closure: vec![],
        }
    }

    fn var(name: &str, op: EnvOp, value: &str) -> EnvVar {
        EnvVar {
            name: name.into(),
            op,
            value: value.into(),
        }
    }

    #[test]
    fn empty_contributions_remove_the_file() {
        let dir = tempfile::tempdir().unwrap();
        let mut modules = BTreeMap::new();
        modules.insert(
            "hx".to_string(),
            state("/gs/store/abc-hx", vec![var("A", EnvOp::Set, "1")]),
        );
        render_env_file(dir.path(), store::GenerationId::new(1), &modules).unwrap();
        // the profile is generation-local now (0025 §C)
        let path = dir.path().join("generations/1/env/profile.sh");
        assert!(path.exists());
        modules.insert("hx".to_string(), state("/gs/store/abc-hx", vec![]));
        // a generation with no contributions carries no profile
        render_env_file(dir.path(), store::GenerationId::new(2), &modules).unwrap();
        assert!(!dir.path().join("generations/2/env/profile.sh").exists());
    }

    #[test]
    fn retained_literal_values_do_not_gain_legacy_expansion_authority() {
        use store::{EnvironmentContribution, StructuredEnvironment};
        let temporary = tempfile::tempdir().unwrap();
        let literal = "$HOME ${HOME} {store} $(tripwire) `tripwire` ' \\\nsecond line";
        let mut module = state(
            "/gs/store/profile with $HOME",
            vec![
                var("LEGACY", EnvOp::Set, "$HOME/bin"),
                var("SAME", EnvOp::Set, "$HOME"),
            ],
        );
        for (name, op, value) in [
            ("LITERAL", EnvOp::Set, literal),
            ("SAME", EnvOp::Set, "$HOME"),
            ("PATH", EnvOp::Prepend, "/declared"),
        ] {
            module.env.push(EnvironmentContribution::Structured(
                StructuredEnvironment::Literal {
                    name: name.into(),
                    op,
                    value: value.into(),
                },
            ));
        }
        module.env.push(EnvironmentContribution::Structured(
            StructuredEnvironment::StorePath {
                name: "PATH".into(),
                op: EnvOp::Prepend,
                path: "commands".into(),
            },
        ));
        let encoded = serde_json::to_vec(&module).unwrap();
        let module = serde_json::from_slice::<store::ModuleState>(&encoded).unwrap();
        let modules = BTreeMap::from([("profile".into(), module)]);
        let profile =
            render_env_file(temporary.path(), store::GenerationId::new(1), &modules).unwrap();
        let marker = temporary.path().join("unexpected-execution");
        let output = std::process::Command::new("/bin/sh")
            .args(["-c", r#"probe="$2"; tripwire() { : > "$probe"; }; . "$1"; printf '%s\0' "$LEGACY" "$LITERAL" "$SAME" "$PATH""#, "env-probe"])
            .arg(profile).arg(&marker)
            .env_clear().env("HOME","/operator-home").env("PATH","/operator-bin")
            .output().unwrap();
        assert!(output.status.success());
        let expected = [
            "/operator-home/bin",
            literal,
            "$HOME",
            "/gs/store/profile with $HOME/commands:/declared:/operator-bin",
        ]
        .join("\0")
            + "\0";
        assert_eq!(output.stdout, expected.as_bytes());
        assert!(!marker.exists());
    }
}
