#!/usr/bin/env python3
"""Regenerate crates/gripsack-exec/src/embedded_frontend.rs from
typescript/src + deno.json/package.json (0035 F6): the frontend is
checked-in generated Rust, so crates.io builds — which have no
typescript/ tree — carry the full evaluator. Run after any frontend
change; the docker test gate diffs for freshness (--check)."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TS = ROOT / "typescript"
OUT = ROOT / "crates/gripsack-exec/src/embedded_frontend.rs"


def rust_raw(text: str) -> str:
    # pick a delimiter the content never collides with
    for hashes in range(1, 8):
        fence = "#" * hashes
        if f'"{fence}' not in text:
            return f'r{fence}"{text}"{fence}'
    raise SystemExit("frontend file defeats raw-string fences up to 7")


entries = []
if (TS / "src").is_dir():
    for path in sorted((TS / "src").rglob("*.ts")):
        rel = path.relative_to(TS / "src").as_posix()
        entries.append((f"src/{rel}", path.read_text()))
for meta in ["deno.json", "package.json"]:
    if (TS / meta).is_file():
        entries.append((meta, (TS / meta).read_text()))

lines = [
    "//! GENERATED by scripts/gen_frontend_embed.py — do not edit.",
    "//! The frontend, vendored as string literals (0035 F6): crates.io",
    "//! builds carry the full evaluator; the docker test gate diffs this",
    "//! file against a fresh regeneration.",
    "",
    "/// (path inside the materialized frontend dir, source) pairs.",
    "#[rustfmt::skip]",
    "pub static FRONTEND_FILES: &[(&str, &str)] = &[",
]
for rel, text in entries:
    lines.append(f'    ("{rel}", {rust_raw(text)}),')
lines.append("];")
content = "\n".join(lines) + "\n"

if "--check" in sys.argv:
    if OUT.read_text() != content:
        print("embedded_frontend.rs is stale — run scripts/gen_frontend_embed.py", file=sys.stderr)
        sys.exit(1)
    print(f"embedded_frontend.rs: fresh ({len(entries)} files)", file=sys.stderr)
else:
    OUT.write_text(content)
    print(f"embedded_frontend.rs: {len(entries)} files", file=sys.stderr)
