#!/usr/bin/env python3
"""Generate the core and frontend diagnostic code constants from one allocation table.

No parser or renderer reads this manifest at runtime. `--check` is the
source-bound build gate; `--self-check` calibrates duplicate-code and
frontend-name rejection without accepting a missing generator as evidence.
"""
from __future__ import annotations

import copy
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "schema/diagnostics.json"
RUST = ROOT / "crates/gripsack-ir/src/diagnostic_codes.rs"
TYPESCRIPT = ROOT / "typescript/src/diagnostic_codes.ts"
CODE = re.compile(r"[EW][0-9]{3}\Z")
RUST_NAME = re.compile(r"[A-Z][A-Z0-9_]*\Z")
FRONTEND_NAME = re.compile(r"[a-z][A-Za-z0-9]*\Z")


def unique_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result = {}
    for name, value in pairs:
        if name in result:
            raise ValueError(f"duplicate manifest field {name!r}")
        result[name] = value
    return result


def validated_rows(document: object) -> list[dict[str, str]]:
    if not isinstance(document, dict) or set(document) != {"registry_version", "codes"}:
        raise ValueError("registry requires exactly registry_version and codes")
    if type(document["registry_version"]) is not int or document["registry_version"] != 1:
        raise ValueError("invalid registry version")
    if not isinstance(document["codes"], list):
        raise ValueError("diagnostic codes must be an array")
    rows = document["codes"]
    if not rows:
        raise ValueError("diagnostic registry must contain allocated codes")
    used_codes: set[str] = set()
    used_rust: set[str] = set()
    used_frontend: set[str] = set()
    previous = ""
    for row in rows:
        if not isinstance(row, dict) or not {"rust", "code", "description"} <= set(row) \
                or set(row) - {"rust", "code", "description", "frontend"}:
            raise ValueError("each code requires rust, code and description with optional frontend")
        rust, code, description = row["rust"], row["code"], row["description"]
        if not isinstance(rust, str) or not RUST_NAME.fullmatch(rust):
            raise ValueError(f"invalid Rust diagnostic name {rust!r}")
        if not isinstance(code, str) or not CODE.fullmatch(code):
            raise ValueError(f"invalid stable diagnostic code {code!r}")
        if not isinstance(description, str) or not description.strip() \
                or any(char in description for char in "\r\n\t"):
            raise ValueError(f"invalid description for {code}")
        if code in used_codes:
            raise ValueError(f"duplicate diagnostic code {code}")
        if rust in used_rust:
            raise ValueError(f"duplicate Rust diagnostic name {rust}")
        if code <= previous:
            raise ValueError(f"diagnostic codes must be in ascending order: {code}")
        used_codes.add(code)
        used_rust.add(rust)
        previous = code
        if "frontend" in row:
            frontend = row["frontend"]
            if not isinstance(frontend, str) or not FRONTEND_NAME.fullmatch(frontend):
                raise ValueError(f"invalid frontend diagnostic name {frontend!r}")
            if frontend in used_frontend:
                raise ValueError(f"duplicate frontend diagnostic name {frontend}")
            used_frontend.add(frontend)
    return rows


def render_rust(rows: list[dict[str, str]]) -> str:
    lines = ["// GENERATED by scripts/gen_diagnostic_registry.py from schema/diagnostics.json.",
             "// Allocate codes in the manifest, not in either frontend.", ""]
    for row in rows:
        lines.extend((f"/// {row['description']}.",
                      f"pub const {row['rust']}: &str = \"{row['code']}\";"))
    return "\n".join(lines) + "\n"


def render_typescript(rows: list[dict[str, str]]) -> str:
    lines = ["// GENERATED by scripts/gen_diagnostic_registry.py from schema/diagnostics.json.",
             "// These are the only core-allocated codes the frontend emits.",
             "export const diagnosticCodes = {"]
    for row in rows:
        if "frontend" in row:
            lines.append(f"  {row['frontend']}: \"{row['code']}\",")
    lines.append("} as const;")
    lines.append("")
    lines.append("export const frontendDiagnosticCodeRegistry = {")
    for row in rows:
        if "frontend" in row:
            lines.append(f"  {row['code']}: true,")
    lines.append("} as const satisfies Record<string, true>;")
    return "\n".join(lines) + "\n"


def reject_mutant(document: dict, expected: str) -> None:
    try:
        validated_rows(document)
    except ValueError as error:
        if expected in str(error):
            print(f"calibration: {expected} rejected on its named property")
            return
        raise ValueError(f"mutant failed for an unrelated reason: {error}") from error
    raise ValueError(f"mutant escaped its required rejection: {expected}")


def main() -> int:
    if sys.argv[1:] not in ([], ["--check"], ["--self-check"]):
        raise ValueError("usage: gen_diagnostic_registry.py [--check|--self-check]")
    document = json.loads(MANIFEST.read_text(), object_pairs_hook=unique_keys)
    rows = validated_rows(document)
    if sys.argv[1:] == ["--self-check"]:
        invalid_version = copy.deepcopy(document)
        invalid_version["registry_version"] = True
        reject_mutant(invalid_version, "invalid registry version")
        duplicate_code = copy.deepcopy(document)
        duplicate_code["codes"][1]["code"] = rows[0]["code"]
        reject_mutant(duplicate_code, "duplicate diagnostic code")
        frontend = [row for row in rows if "frontend" in row]
        duplicate_frontend = copy.deepcopy(document)
        target = next(row for row in duplicate_frontend["codes"] if row["rust"] == frontend[1]["rust"])
        target["frontend"] = frontend[0]["frontend"]
        reject_mutant(duplicate_frontend, "duplicate frontend diagnostic name")
        print("diagnostic registry calibration: 3 named mutants rejected")
        return 0
    rendered = ((RUST, render_rust(rows)), (TYPESCRIPT, render_typescript(rows)))
    if sys.argv[1:] == ["--check"]:
        stale = [str(path.relative_to(ROOT)) for path, content in rendered
                 if not path.is_file() or path.read_text() != content]
        if stale:
            raise ValueError(f"stale diagnostic registry outputs: {', '.join(stale)}")
        print(f"diagnostic registry: {len(rows)} unique core codes, "
              f"{sum('frontend' in row for row in rows)} frontend allocations; generated files fresh")
        return 0
    for path, content in rendered:
        path.write_text(content)
        print(f"generated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError) as error:
        print(f"diagnostic registry: {error}", file=sys.stderr)
        raise SystemExit(1) from error
