// GENERATED by scripts/gen_diagnostic_registry.py from schema/diagnostics.json.
// Allocate codes in the manifest, not in either frontend.

/// Malformed IR or closed tagged-field grammar.
pub const MALFORMED: &str = "E000";
/// Unsupported IR version.
pub const VERSION: &str = "E100";
/// Missing declared module dependency.
pub const UNKNOWN_DEPENDENCY: &str = "E101";
/// Invalid destination path.
pub const BAD_DESTINATION: &str = "E102";
/// Explicit steps mixed with incompatible module fields.
pub const STEPS_WITH_FIELDS: &str = "E103";
/// Unknown step or prerequisite.
pub const UNKNOWN_STEP: &str = "E104";
/// Duplicate or reserved step identifier.
pub const DUPLICATE_STEP: &str = "E106";
/// Undeclared resource reference.
pub const UNKNOWN_RESOURCE: &str = "E107";
/// Unsupported ownership mode.
pub const UNSUPPORTED_MODE: &str = "E108";
/// Invalid verify-path shape.
pub const VERIFY_PATH_SHAPE: &str = "E109";
/// Missing source file.
pub const MISSING_SOURCE: &str = "E110";
/// Conflicting physical destination.
pub const DUPLICATE_DESTINATION: &str = "E111";
/// Probe binding failed to reach a fixpoint.
pub const PROBE_UNSTABLE: &str = "E112";
/// Unsupported frontend probe request.
pub const PROBE_UNSUPPORTED: &str = "E113";
/// Unknown interpolation placeholder.
pub const UNKNOWN_PLACEHOLDER: &str = "E114";
/// Unsafe source or destination path.
pub const BAD_PATH: &str = "E115";
/// Unsafe module identifier.
pub const INVALID_MODULE_NAME: &str = "E116";
/// Invalid environment variable identifier.
pub const INVALID_ENV_NAME: &str = "E117";
/// Ambiguous source pin from multiple fetch steps.
pub const UNPINNABLE_STEPS: &str = "E118";
/// Aliased physical destination.
pub const DESTINATION_ALIAS: &str = "E119";
/// Cyclic module step prerequisites.
pub const STEP_CYCLE: &str = "E120";
/// Step prerequisite crosses forbidden phase order.
pub const STEP_PHASE_ORDER: &str = "E121";
/// Unknown dependency edge kind.
pub const UNKNOWN_EDGE: &str = "E122";
/// Build dependency environment name collision.
pub const BUILD_DEP_ENV_COLLISION: &str = "E123";
/// Workspace output executor unavailable.
pub const WORKSPACE_EXEC_UNAVAILABLE: &str = "E124";
/// Duplicate workspace catalog name.
pub const DUPLICATE_WORKSPACE_OUTPUT: &str = "E125";
/// Missing, wrong-kind, or incompatible workspace reference.
pub const UNKNOWN_WORKSPACE_REF: &str = "E126";
/// Cycle among workspace dependency roles.
pub const WORKSPACE_CYCLE: &str = "E127";
/// Command reference in an invalid workspace context.
pub const BAD_WORKSPACE_CONTEXT: &str = "E128";
/// Invalid mandatory workspace source span.
pub const BAD_WORKSPACE_SPAN: &str = "E129";
/// Workspace value outside the admitted grammar.
pub const INVALID_WORKSPACE_VALUE: &str = "E130";
/// Required workspace graph edge missing or substituted.
pub const REQUIRED_WORKSPACE_EDGE_MISSING: &str = "E131";
/// Unsafe host entrypoint or lockfile identifier.
pub const INVALID_HOST_NAME: &str = "E132";
/// Fetch or source resolution failed.
pub const EXEC_FETCH: &str = "E201";
/// Execution step failed.
pub const EXEC_STEP: &str = "E301";
/// Module verification failed.
pub const EXEC_VERIFY: &str = "E302";
/// Invalid configuration.
pub const CONFIG: &str = "E400";
